### ISSUE TITLE
Types & Grammar (Tipos e Gramática) - Apêndice A

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#14]

**Comment by alinedmelo** [comment]
Olá Cezar,

Tenho interesse em contribuir e traduzir esse capítulo. É só dar um fork no projeto, traduzir o MD e quando finalizado dar o PR?

**Comment by cezaraugusto** [comment]
Oi Aline, obrigado pelo interesse! Isso mesmo que você falou, e visto que os capítulos são muito grandes, pode mandar blocos pequenos traduzidos e mandar outros PRs em seguida.

Vou marcar este como "em progresso", caso tenha dúvidas sobre a tradução de certos termos, pode consultar o [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md).

**Comment by alinedmelo** [comment]
Legal Cezar, vou iniciar por aqui nas minhas horas vagas. Obrigada!

**Comment by alinedmelo** [comment]
Capítulo concluído!
Traduzido, revisado e dado merge.
