### ISSUE TITLE
Scope & Closures (Escopos e Encerramentos) - Índice

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#16]

**Comment by ebragaparah** [comment]
Esse volume é sensacional. Eu já li, gostaria de ajudar aqui também. Posso pegar este? Terminando este, vou pegando os outros capítulos.

**Comment by cezaraugusto** [comment]
@ebragaparah 👍

**Comment by ebragaparah** [comment]
e aí, @cezaraugusto. começando a trabalhar agora, que a semana acabou, vi que essa parte já foi traduzida, hahaha. dá uma olhada. se sim, acho que podemos mover pra done.

**Comment by cezaraugusto** [comment]
@ebragaparah é verdade, os índices de todos os capítulos já foram traduzidos. Voei.

Fecha #7 #17, #18, #28, #30, #40, #51

cc @gabsprates

**Comment by gabsprates** [comment]
\o/
