### ISSUE TITLE
Scope & Closures (Escopos e Encerramentos) - Capítulo 1

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#19]

**Comment by robsongomes** [comment]
É pra traduzir 'closures'? Eu acho a palavra tão difundida, além de ficar meio estranho 'fechamentos'.

**Comment by gabsprates** [comment]
Concordo com vc @robsongomes. Estou traduzindo o capítulo 3 do _Up & Going_, que faz um resumo da série, e onde fala **closure** eu não traduzi, deixei assim mesmo.
Até mesmo porque tem o [WORDREFERENCE.md](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md) no projeto.

**Comment by cezaraugusto** [comment]
@robsongomes @gabsprates 

Alguns livros traduzidos para Português traduzem _closures_ como _encerramentos_. Assim como alguns traduzem _loops_ como _laços_. E na didática de pseudo-linguagem é assim que é ensinado também.

Acho legal (e é o que eu tenho feito nas minhas partes da tradução) traduzir (caso o termo não tenha tradução ainda, edite o [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md) por conta da coesão) e colocar junto em parênteses o termo original. Exemplo:

> **Encerramentos (Closures)**
> 
> Lorem ipsum...

O importante é manter uma coesão entre todos os livros e ampliar o público-alvo para o maior número de pessoas, seja quem tem background em CC, quem busca recursos primeiro em inglês, etc.

**Comment by gabsprates** [comment]
Beleza :+1:

**Comment by cezaraugusto** [comment]
Para todos os fins, uma boa referência para as traduções é o [MSDN](https://msdn.microsoft.com/pt-br/library/d1et7k7c%28v=vs.94%29.aspx) (eu contribuo pro MDN e por ser aberto cria diversas divergências, o MSDN é feito pela própria MS). Aliás, como o @robsongomes deve ter visto por lá, eles traduzem closure como fechamento. Acho o termo muito vago também, fico com encerramento por ora.
