### ISSUE TITLE
Scope & Closures (Escopos e Encerramentos) - Capítulo 2

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#20]

**Comment by diegofaria** [comment]
quero fazer essa parte

**Comment by cezaraugusto** [comment]
Oi Diego, legal! 🎉 

Vou deixar a issue aberta pra voce. Terminando faz um PR e a gente te coloca na listinha 👻 . 
Obrigado!

**Comment by cezaraugusto** [comment]
@diegofaria ainda com tempo para essa tradução? Dá um alô caso não estiver. Fechamos o primeiro livro e esse é o próximo, se for o caso podemos te colocar em outro capítulo com uma margem maior.

**Comment by raribeiro** [comment]
@cezaraugusto acabei esbarrando aqui, acabei traduzindo uma parte, dou continuidade? Estou lendo e traduzindo. Mando um PR do que já fiz? Faltou só uma parte, o @diegofaria não deu retorno.
