### ISSUE TITLE
Scope & Closures (Escopos e Clausuras) - Capítulo 3

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#21]

**Comment by andrediasgustavo** [comment]
Quero fazer essa parte!

**Comment by cezaraugusto** [comment]
Legal @andrediasgustavo! Vou deixar ela aberta enquanto você produz. Terminando manda o PR pro  branch `portuguese-translation` e eu te coloco na nossa listinha 🎉  

Se houverem dúvidas em relação à gramática, temos o [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md) para todas as horas. :cat:

**Comment by cezaraugusto** [comment]
@andrediasgustavo ainda com tempo para essa tradução? Dá um alô caso não estiver. Fechamos o primeiro livro e esse é o próximo, se for o caso podemos te colocar em outro capítulo com uma margem de tempo maior.

**Comment by gmsecrieru** [comment]
@andrediasgustavo Vou dar início aos trabalhos para seguirmos com a tradução deste livro, visto que já temos os capítulos 1 e 2 finalizados. Fique à vontade pra contribuir! :)

**Comment by rogefm** [comment]
Olá o/
Eu cheguei nessa parte do livro, não sei como está o progresso, mas vou precisar traduzir para poder lê -lo. Gostaria de saber se poderia estar pegando esse resto de capitulo para mim, caso ele esteja abandonado ^^
Até o/

**Comment by cezaraugusto** [comment]
parece ótimo, obrigado!

/cc @gmsecrieru como anda seu progresso? Algum meio do @Rogerfm contribuir com seu progresso?

**Comment by cezaraugusto** [comment]
Fechado pelo eb82149
