### ISSUE TITLE
Scope & Closures (Escopos e Clausuras) - Capítulo 4

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#22]

**Comment by nersoh** [comment]
Se me permite, gostaria de traduzir essa parte! 👊

**Comment by cezaraugusto** [comment]
@nersoh claro, obrigado por contribuir 👶 . Vou deixar a issue aberta, quando terminar sua tradução manda o PR pro branch `portuguese-translation` e eu te incluo na nossa listinha :tada:

Caso tenha alguma dúvida em relação aos termos técnicos para tradução, veja o nosso [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md). Obrigado!

**Comment by cezaraugusto** [comment]
@nersoh ainda com tempo para essa tradução? Dá um alô caso não estiver. Fechamos o primeiro livro e esse é o próximo, se for o caso podemos te colocar em outro capítulo com uma margem de tempo maior.

**Comment by nersoh** [comment]
Opa, @cezaraugusto. Agora estou, essas últimas semanas foram tensas p/ mim. Mas vou tentar traduzir algo já essa próxima semana. 😄

**Comment by gabsprates** [comment]
Creio que podemos fechar esta Issue, graças ao PR #69.

**Comment by cezaraugusto** [comment]
Fechando, obrigado @gabsprates
