### ISSUE TITLE
Scope & Closures (Escopos e Closures) - Capítulo 5

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#23]

**Comment by raribeiro** [comment]
@cezaraugusto assina essa issue pra mim por favor, estou fazendo a leitura do itens traduzidos e separando 30 min diários para traduzir aqui no meu fork. 

Vocês criaram um canal no slack?

**Comment by cezaraugusto** [comment]
Oi @raribeiro, tá contigo.

Não temos um canal de comunicação, mas é uma grande ideia. Geralmente eu falo com o pessoal pelo twitter [@cezaraugusto](https://twitter.com/cezaraugusto) (DM aberta). Se quiser pode abrir uma issue pra debate sobre isso, acho que o pessoal vai curtir.

Peço que junto da tradução se guie (e ajude também) pelo [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md). E dê sua opinião na issue #68. Obrigado.

**Comment by gabsprates** [comment]
@cezaraugusto @raribeiro, um canal no Slack seria bacana, mas será que não seria mais interessante fazermos um grupo em algum canal (Slack) brasileiro de front-end?
É só uma ideia mesmo, falo porque por exemplo, tem o Slack do BrazilJS, aí talvez ter um grupo lá do YDKJS, entenderam?

**Comment by raribeiro** [comment]
@gabsprates acho supoer válido cara, as vezes precisamos de algumas comunicações rápidas. Outro detalhe @cezaraugusto  já, pensaram na viabilidade de levar o projeto para o Gitbook?

@gabsprates e @cezaraugusto no slack estou no ctgroups e no feds, mas podemos pensar em criar lá dentro no BrazilJS, sem problema.

**Comment by cezaraugusto** [comment]
@raribeiro o livro é licenciado pela O'Reilly. Tudo o que podemos fazer é traduzir e desde que esteja no GitHub (vide [README](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/README.md)). A cópia e/ou redistribuição por qualquer outro meio é proibida, inclusive o gitbook. 

Mais info aqui: https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue+gitbook

**Comment by raribeiro** [comment]
@cezaraugusto sim eu vi, mas podemos entrar em contato com O'Reilly, afinal ele vai continuar no github, mas acredito que irá estar mais acessível a grande massa, você pode tentar falar com eles?

**Comment by cezaraugusto** [comment]
@raribeiro, o Kyle em uma issue do repo original fala que [o gitbook não é viável para o projeto](https://github.com/getify/You-Dont-Know-JS/issues/537) e eu realmente não quero burlar nenhuma regra. Na tradução do [JavaScript Eloquente](https://github.com/braziljs/eloquente-javascript/) pelo @ericdouglas aconteceu uma divergência entre os tradutores e o autor, e rolou uma desmotivada pela equipe até onde eu sei, o que eu realmente não desejo pro nosso trabalho.

Eu entendo que o gitbook é muito melhor para leitura, mas visto que o autor discorda, não vou medir forças. Espero que entenda.

**Comment by raribeiro** [comment]
@cezaraugusto perfeito!

**Comment by gabsprates** [comment]
Vou criar uma Issue sobre canais de comunicação, pode ser? @cezaraugusto @raribeiro

**Comment by cezaraugusto** [comment]
@raribeiro como anda essa etapa? Dá um alô se estiver sem tempo e (caso já tenha produzido) envie o conteúdo que tiver disponível, esse livro é o próximo e seria legal se pudermos fecha-lo antes dos outros. ;)

**Comment by raribeiro** [comment]
@cezaraugusto ! Estou fechando ele e lendo outras etapas no tempo vago, mando essa semana sem falta :+1: Deixei uma mensagem pra você no Telegram, chegou a ver?

**Comment by gabsprates** [comment]
Boa tarde @raribeiro, como anda a tradução? Se estiver sem tempo nos avise. Caso tenha algo já traduzido, envie o que já tem, para podermos agilizar a revisão. (:

**Comment by gabsprates** [comment]
Bom, ficarei encarregado dessa aqui, já estamos caminhando para o final do livro, melhor adiantar o que der.

**Comment by alinedmelo** [comment]
Pessoal, vou ficar com esse ;)
