### ISSUE TITLE
Scope & Closures (Escopos e Clausuras) - Apêndice B

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#25]

**Comment by holandajunior** [comment]
Posso traduzir esse!

**Comment by cezaraugusto** [comment]
Legal @holandajunior, tá contigo.

Caso tenha dúvidas sobre a tradução de certos termos, veja o nosso [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md). 

Peço que consulte também o #68 para ver como estamos fazendo as traduções. 👍

**Comment by holandajunior** [comment]
Ok, @cezaraugusto. Obrigado pelas informações.

**Comment by gabsprates** [comment]
Issue fechada no PR #118
