### ISSUE TITLE
Up & Going (Iniciando) - Capítulo 2

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#4]

**Comment by thismarcoantonio** [comment]
Pequena correção em (entree):

> Por exemplo, arrays são por padrão convertidas para strings por simplesmente se juntarem todos os valores com vírgulas (,) ## **entree** elas. Você pode pensar que duas arrays com o mesmo conteúdo são iguais ==, quando na verdade não são:

**Comment by gabsprates** [comment]
@thismarcoantonio pode mandar um PR com a correção?
