### ISSUE TITLE
Async & Performance (Async & Performance) - Capítulo 1

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#41]

**Comment by zavjs** [comment]
Quero fazer essa parte! :D

**Comment by cezaraugusto** [comment]
Legal @zavjs, tá contigo.

Caso tenha dúvidas sobre a tradução de certos termos, veja o nosso [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md). Peço que consulte também o #68 para ver como estamos fazendo as traduções. 👍

**Comment by zavjs** [comment]
Legal, valeu.

Não encontrei o termo 'callback function' na WORDREFERENCE. Por enquanto coloquei 'função de retorno', com parenteses para a palavra original, em caso de necessidade de alteração.

**Comment by cezaraugusto** [comment]
@zavjs, poderia usar o termo "_função de callback_"?

O termo _callback_ já é consagrado no uso em Português, acho que seria melhor mantê-lo. Poderia usar junto da definição em Português. Ex.: **função de callback (retorno)**.

Vou atualizar o WORDREFERENCE com a sua observação. Obrigado.

**Comment by zavjs** [comment]
Claro, anotado. Obrigado!

**Comment by zavjs** [comment]
Vou anotando aqui, os termos mais ambíguos para que possamos decidir a melhor tradução. Até agora, tenho 3 (quase 4):
- low-level 
- threading/thread (deixei no original, por enquanto)
- loop (traduzi como 'laço')
- event loop (traduzi como 'laço de eventos', baseado na supracitada)

**Comment by zavjs** [comment]
- Run-to-completion (executar-à-compleção? haha)

**Comment by gabsprates** [comment]
Acredito que "low-level" pode ser _baixo nível_, que é um termo comum na computação, assim como usar _laço_ para "loop".

**Comment by cezaraugusto** [comment]
@zavjs 
- low-level = **baixo nível (low-level)**
- threading/thread (deixei no original, por enquanto) **qual contexto?**
- loop (traduzi como 'laço') Termo consagrado: **Manter como loop**
- event loop (traduzi como 'laço de eventos', baseado na supracitada) **loop de eventos**

**Comment by gabsprates** [comment]
@cezaraugusto e @zavjs, me parece que não há nada pendente neste capítulo. Confere?

**Comment by cezaraugusto** [comment]
oops verdade, obrigado @gabsprates, fechando

**Comment by cezaraugusto** [comment]
fechado pelo #115
