### ISSUE TITLE
Up & Going (Iniciando) - Capítulo 3

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#5]

**Comment by gabsprates** [comment]
Como está até aqui?

**Comment by cezaraugusto** [comment]
Oi @gabsprates, obrigado pelo interesse.

Está aberto, caso queira contribuir dá um alô que eu designo pra você :boom:

**Comment by gabsprates** [comment]
Ok, quero sim! (:

**Comment by ebragaparah** [comment]
Oi! Essa parte está sendo traduzida, pessoal? Vi que o @gabsprates pegaria, mas a tag de "disponível para tradução" continua. Se estiver precisando de tradução, topo pegar!

**Comment by gabsprates** [comment]
Olá @ebragaparah, estou trabalhando nisso sim, num [fork meu](https://github.com/gabsprates/You-Dont-Know-JS/tree/up-and-going_cp3) aqui

**Comment by gabsprates** [comment]
Pronto! (:
