### ISSUE TITLE
ES6 & beyond (ES6 e Além) - Apêndice A

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/You-Dont-Know-JS#60]

**Comment by ailton07** [comment]
Gostaria de começar a contribuir traduzindo esta parte

**Comment by cezaraugusto** [comment]
Legal @ailton07 tá contigo. Quando estiver pronto faça o PR pro branch `portuguese-translation`. 
Estamos dividindo nossas partes em blocos curtos para facilitar a revisão. Mais info na #68.

Sempre que tiver dúvidas referentes ao jargões da linguagem, consulte o [WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md).

Obrigado
